/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    trainers: Trainer;
    bookings: Booking;
    supplements: Supplement;
    members: Member;
    'bulk-attendance': BulkAttendance;
    attendance: Attendance;
    'page-settings': PageSetting;
    trial: Trial;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    trainers: TrainersSelect<false> | TrainersSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    supplements: SupplementsSelect<false> | SupplementsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'bulk-attendance': BulkAttendanceSelect<false> | BulkAttendanceSelect<true>;
    attendance: AttendanceSelect<false> | AttendanceSelect<true>;
    'page-settings': PageSettingsSelect<false> | PageSettingsSelect<true>;
    trial: TrialSelect<false> | TrialSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  cloudinary_id?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainers".
 */
export interface Trainer {
  id: string;
  name: string;
  title?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (string | null) | Media;
  /**
   * Banner image for trainers page header (optional)
   */
  bannerImage?: (string | null) | Media;
  /**
   * Background image for the white content section below header (optional)
   */
  contentBackgroundImage?: (string | null) | Media;
  yearsExp?: number | null;
  clients?: number | null;
  rating?: number | null;
  specialties?:
    | {
        specialty?: string | null;
        id?: string | null;
      }[]
    | null;
  achievements?:
    | {
        achievement?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Trainer booking requests from customers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: string;
  name: string;
  phone: string;
  email: string;
  trainer: string | Trainer;
  preferredTime?: ('Morning (6 AM - 12 PM)' | 'Afternoon (12 PM - 6 PM)' | 'Evening (6 PM - 10 PM)') | null;
  goals?:
    | {
        goal?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  /**
   * Update booking status as you process requests
   */
  status?: ('pending' | 'confirmed' | 'completed' | 'cancelled') | null;
  /**
   * Scheduled booking date (set after confirmation)
   */
  bookingDate?: string | null;
  /**
   * Internal notes for admin use only
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplements".
 */
export interface Supplement {
  id: string;
  name: string;
  description?: string | null;
  price: number;
  originalPrice?: number | null;
  image?: (string | null) | Media;
  /**
   * Banner image for supplements page header (optional)
   */
  bannerImage?: (string | null) | Media;
  /**
   * Background image for the white content section below header (optional)
   */
  contentBackgroundImage?: (string | null) | Media;
  badge?: string | null;
  badgeColor?: ('red' | 'blue' | 'yellow' | 'green') | null;
  category?: ('Protein' | 'Pre-Workout' | 'Post-Workout' | 'Vitamins') | null;
  benefits?:
    | {
        benefit?: string | null;
        id?: string | null;
      }[]
    | null;
  specs?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Search by Member ID, Name, Phone, or CNIC
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  /**
   * Unique Member ID (e.g., GYM001)
   */
  memberId: string;
  name: string;
  /**
   * Format: 03XXXXXXXXX
   */
  phone: string;
  /**
   * Format: 12345-1234567-1
   */
  cnic: string;
  feeStartDate: string;
  /**
   * Amount paid in PKR
   */
  pricePaid: number;
  /**
   * Auto-calculated based on fee date
   */
  status?: ('Active' | 'Expired') | null;
  /**
   * Auto-calculated days remaining
   */
  daysLeft?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mark attendance for multiple members at once
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulk-attendance".
 */
export interface BulkAttendance {
  id: string;
  /**
   * Select the date for attendance
   */
  attendanceDate: string;
  /**
   * Select all members who are present
   */
  presentMembers?: (string | Member)[] | null;
  /**
   * Total members marked present
   */
  totalPresent?: number | null;
  /**
   * Optional notes for this attendance session
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual attendance records (auto-managed by bulk attendance)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance".
 */
export interface Attendance {
  id: string;
  member: string | Member;
  date: string;
  /**
   * Attendance marked
   */
  checkmark?: boolean | null;
  timestamp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage banner images and settings for each page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-settings".
 */
export interface PageSetting {
  id: string;
  /**
   * Select the page to configure
   */
  pageName: 'home' | 'trainers' | 'supplements' | 'pricing';
  /**
   * Banner image displayed at the top of the page (recommended: 1920x500px)
   */
  bannerImage?: (string | null) | Media;
  /**
   * Main heading text for the banner
   */
  bannerTitle?: string | null;
  /**
   * Description text below the main heading
   */
  bannerSubtitle?: string | null;
  /**
   * Overlay darkness on banner image for better text readability
   */
  bannerOverlayColor?: ('dark' | 'medium' | 'light' | 'none') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the Trial section content on home page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trial".
 */
export interface Trial {
  id: string;
  /**
   * Main heading for trial section
   */
  title: string;
  /**
   * Description text
   */
  description: string;
  /**
   * Background image for trial section
   */
  backgroundImage?: (string | null) | Media;
  /**
   * List of features with checkmarks
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Form heading
   */
  formTitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders from supplements store
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  customerName: string;
  email?: string | null;
  phone: string;
  address: string;
  items: {
    productName: string;
    quantity: number;
    price: number;
    subtotal: number;
    id?: string | null;
  }[];
  totalAmount: number;
  paymentMethod: 'cash' | 'whatsapp';
  /**
   * Order status
   */
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  /**
   * Internal notes about the order
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'trainers';
        value: string | Trainer;
      } | null)
    | ({
        relationTo: 'bookings';
        value: string | Booking;
      } | null)
    | ({
        relationTo: 'supplements';
        value: string | Supplement;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'bulk-attendance';
        value: string | BulkAttendance;
      } | null)
    | ({
        relationTo: 'attendance';
        value: string | Attendance;
      } | null)
    | ({
        relationTo: 'page-settings';
        value: string | PageSetting;
      } | null)
    | ({
        relationTo: 'trial';
        value: string | Trial;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinary_id?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainers_select".
 */
export interface TrainersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  bio?: T;
  photo?: T;
  bannerImage?: T;
  contentBackgroundImage?: T;
  yearsExp?: T;
  clients?: T;
  rating?: T;
  specialties?:
    | T
    | {
        specialty?: T;
        id?: T;
      };
  achievements?:
    | T
    | {
        achievement?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  trainer?: T;
  preferredTime?: T;
  goals?:
    | T
    | {
        goal?: T;
        id?: T;
      };
  notes?: T;
  status?: T;
  bookingDate?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplements_select".
 */
export interface SupplementsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  originalPrice?: T;
  image?: T;
  bannerImage?: T;
  contentBackgroundImage?: T;
  badge?: T;
  badgeColor?: T;
  category?: T;
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  specs?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  memberId?: T;
  name?: T;
  phone?: T;
  cnic?: T;
  feeStartDate?: T;
  pricePaid?: T;
  status?: T;
  daysLeft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulk-attendance_select".
 */
export interface BulkAttendanceSelect<T extends boolean = true> {
  attendanceDate?: T;
  presentMembers?: T;
  totalPresent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance_select".
 */
export interface AttendanceSelect<T extends boolean = true> {
  member?: T;
  date?: T;
  checkmark?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-settings_select".
 */
export interface PageSettingsSelect<T extends boolean = true> {
  pageName?: T;
  bannerImage?: T;
  bannerTitle?: T;
  bannerSubtitle?: T;
  bannerOverlayColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trial_select".
 */
export interface TrialSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  backgroundImage?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  formTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customerName?: T;
  email?: T;
  phone?: T;
  address?: T;
  items?:
    | T
    | {
        productName?: T;
        quantity?: T;
        price?: T;
        subtotal?: T;
        id?: T;
      };
  totalAmount?: T;
  paymentMethod?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}